### ISSUE TITLE
TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by Guisch** [feross/simple-websocket#15]
Hi,

I don't really know why it's happening but since I updated all my modules, i get this error (I tried to roll-back the previous version of the module and I don't get the error any-more):

```
/node_modules/simple-websocket/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/root/project/node_modules/simple-websocket/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/project/node_modules/simple-websocket/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)

npm ERR! Linux 4.4.38-std-1
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
```

I'm not using directly simple-websocket but I use it throught webtorrent-hybrid.
If you need more info ask me !

**Comment by DiegoRBaquero** [comment]
Requires NodeJS v6+

**Comment by Guisch** [comment]
Change nothing

```
/node_modules/simple-websocket/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/node_modules/simple-websocket/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/node_modules/simple-websocket/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)

npm ERR! Linux 4.4.38-std-1
npm ERR! argv "/root/.nvm/versions/node/v7.5.0/bin/node" "/root/.nvm/versions/node/v7.5.0/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! Exit status 1
```

**Comment by DiegoRBaquero** [comment]
@Guisch Try v6, let's rule out semver-major incompatibility.

**Comment by lpinca** [comment]
The supported Node.js versions (4, 6, 7) should all work as `ws` is tested against [them](https://github.com/websockets/ws/blob/92d869695978dc73350be6590456c83ac9e80593/.travis.yml).

**Comment by Guisch** [comment]
I confirlm, not working on v6.9.4, v6.9.5 and v6.0.0 also for me (with a complete re-installation of all the modules).

**Comment by DiegoRBaquero** [comment]
Well, that's very weird. Same error??

**Comment by Guisch** [comment]
Yep, exactly the same.

**Comment by lpinca** [comment]
@Guisch add this in the module where you require `simple-websocket` and please report the result:

```js
console.log(process.versions);
```

**Comment by Guisch** [comment]
@lpinca I got this (I do not require simple-websocket but webtorrent-hybrid, I don't know if it changes something).

```
 { http_parser: '2.5.0',
  node: '4.2.6',
  v8: '4.5.103.35',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '46',
  openssl: '1.0.2g-fips' }
```

**Comment by DiegoRBaquero** [comment]
> node: '4.2.6'

remove older versions and try `nvm use 6`

**Comment by lpinca** [comment]
I'm not sure why this issue is open here then but it doesn't matter. As you can see the Node.js version you are using is 4.2.6. You need 4.5.0 or greater.

I think you have multiple conflicting Node.js version installed. I don't know what Linux distribution you are using but try to remove the Node.js version that is installed with apt-get, dnf or whatever and only use nvm.

**Comment by Guisch** [comment]
Tha's obvious... Thanks for your time. It's now working ! 👍
